### ISSUE TITLE
expected class-name before '{' token

### ISSUE THREAD

**Issue by oneluis** [pkourany/Adafruit_PCD8544_IDE#2]
Veryfing code using this library in Particle Build fails with this error:

```
Adafruit_PCD8544/Adafruit_PCD8544.h:51:46: error: expected class-name before '{' token
 class Adafruit_PCD8544 : public Adafruit_GFX {
                                              ^
```

**Comment by pkourany** [comment]
@oneluis, did you include the Adafruit_GFX library when you compiled?

**Comment by colinta** [comment]
I made the same mistake, just needed to include Adafruit_GFX like you said.  Thanks!
